### ISSUE TITLE
Offline echo dot

### ISSUE THREAD

**Issue by kisst6** [christianTF/LoxBerry-Plugin-Alexa2Lox#17]
Hello All,

I installed this plugin, and connected to the Amazon (via 2 fact pass).
I see my device in the "Gefundene Geräte" list, but Its offline.
When I send a command ex. playerstate, the answer is:

B&B Technik OG
device --> Nappali
playerstate

Calling /opt/loxberry/webfrontend/htmlauth/plugins/alexa2lox/start.sh --device "Nappali" --playerstate  ...

Used UDP port from MQTT Gateway: 11884
Optionen:
ACTION:
DEVICE: Nappali
Full command: --device Nappali --playerstate
Prüfe auf Environment Variablen
Von PHP aufgerufen - Umgebungsvariablen sollten gesetzt sein
EMAIL: xxxx@gmail.com
MFA_SECRET: xxxx xxxx xxxx xxxx xxxx xxxx xxxx

Alexa2Lox Routinen werden verwendet...
Playerstatus
Player Nappali abfragen...
Title:
Album:
Interpret:
Volume:
Muted: null
Repeat:
Shuffle:
Bild:
Status:
Mediaid:
Queueid:
Provider:
Sende an MQTT Gateway...

What did I wrong?

Many thanks in advance.

**Comment by christianTF** [comment]
Sorry for not answering your query.
However I'll close the issue as I think the question is already obsolete.
Cheers, Christian
